name : riverpod_mvvm
description : Simple implementation for Model-View-ViewModel Architecture
version : 0.0.1
homepage : https://github.com/wooxist/riverpod_mvvm

environment :
  sdk : '>=3.0.5 <4.0.0'
  flutter : ">=3.3.0"

dependencies :
  flutter :
    sdk : flutter

  flutter_riverpod : ^2.3.6

dev_dependencies :
  flutter_test :
    sdk : flutter
  flutter_lints : ^2.0.0

flutter :